### ISSUE TITLE
Typeahead for RSVPs from API data

### ISSUE THREAD

**Issue by AbhiAgarwal** [TechAtNYU/event-checkin#15]
Write logic for Typeahead so people can select their name. Append this to a "admin" mode. Basically enable this the same way we enable configure. This will be easier so we don't have to do the whole Login with Facebook nightmare. 

Think about how to do this, though.

**Comment by AbhiAgarwal** [comment]
@ethanresnick started building the typeahead today. Ran into an issue:

For the RSVP data we have IDs. We don't really have names of people that are accessible for when there's no e-board member logged into that form. Also a security risk to let people do a typeahead on public domain. How should we do this? 

A solution from my end is:
1. The typeahead works only when an e-board member is logged into the API. So there can be a incognito and a normal window open. Incognito => when you don't have an account already, normal => when you have a normal account already. How does this seem? Do you have a better solution?
2. Do a typeahead that matches whole names or at least first names then suggests the last name.
3. Doesn't matter if we expose their names. We're not giving out more details than that anyways. 

I'll think about this more in the morning. Just wanted to lay out some foundation here for us (partially me) to get started thinking on more ideas.

Also:

I wrote a short script that takes Facebook RSVPs (from events) and cross checks them against our API. If there's any matching Facebook IDs then it adds them to the RSVP list for the event on the API. [Here](https://github.com/TechAtNYU/overlord/blob/master/overlord/events.py). Should help us automate things.

**Comment by AbhiAgarwal** [comment]
Also:

I wrote a short script that takes facebook RSVPs (from events) and cross checks them against our API. If there's any matching Facebook IDs then it adds them to the RSVP list for the event on the API. [Here](https://github.com/TechAtNYU/overlord/blob/master/overlord/events.py). Should help us automate things.

**Comment by AbhiAgarwal** [comment]
Have an initial version. Depending on how successful the typeahead is I will re-write it.

Not happy with `rsvp_person`, some of the formatting, `MainCtrl`, and some of the partials that dictate what users/e-board member see.

**Comment by juliepanda** [comment]
What if we can have an eboard member laptop out when for general sign-in (a list of all of the names)? And, if you RSVP'd on your own laptop, then you can use that and just click your own name off (only one name showing)? Upon visiting the site, it can log you in whether you are on the eboard or not and show different list.

**Comment by AbhiAgarwal** [comment]
yes that's what's happening :D if you click it right now as a e-board member you see the list! if you're not then it normally checks you in :)

**Comment by AbhiAgarwal** [comment]
But the own laptop thing isn't perfect yet. It assumes it's a public computer so it logs you out of Facebook. I shall fix that soon!

**Comment by AbhiAgarwal** [comment]
If you go here you can see a sample: http://checkin.techatnyu.org/#/560c79a2b46d1b9ca0250519/true

**Comment by juliepanda** [comment]
Ohhhhh, cool! When I was at the ReactJS event yesterday, one of the comments was def that the process of logging into facebook on a public laptop to check-in makes ppl feel awkward/uncomfortable. Good to know that we are fixing it!

**Comment by AbhiAgarwal** [comment]
Yeah I agree with that @ycp217. It's because we didn't have an RSVP system and didn't have a way to add people's data into the API easily. We need their FacebookID, which is really important since our API won't be able to log you in with the same user ID next time. We'll fix it given more time + testing!
