### ISSUE TITLE
Rethink everything

### ISSUE THREAD

**Issue by AbhiAgarwal** [TechAtNYU/event-checkin#21]
with @brentdur. What's the most optimal and non intrusive way to get people to checkin at our event?  Their experience of doing anything should be minimal. This means - how can we make them do the least work and feel the least worried about their data when checking into our event. Let's re-think our whole approach to checking people into our event and remove the Login with Facebook (from checkin).

I think it worked well and we get a lot out of it, but the experience of coming to an event is sometimes a little worse off when someone makes you login through your Facebook at the beginning of the event. This might be worse off for us in terms of data collection, but let us try and think how we can solve this. At the end of the day we want to build things that are non-intrusive, but still valuable for us.

Perhaps a way could be to record their Name and Email, and then either email them or get their Facebook ID through the Facebook Graph Search, and manually add them to the API (at the beginning -> then we can automize it). OR we can send a link to their email with a unique checkin URL that they can use on their own computer.

During the break @brentdur and I are going to try new things to see how we can optimize this. Right now, I'm leaning towards getting rid of login with Facebook for Checkin permanently. Lets see where we can go from there!

Let's try and stay away from saying that the current approach is bad. That's not too productive! Let's think about actual better experiences that we can _build_ and benefit off of.

That said. We can build things before or after events that can help us. The sky is literally the limit here. We introduced RSVP this semester, which was beneficial to checking people in. How can we either adapt that or promote it better (etc) or how can we change it (etc).

Convo with [Brenton](https://gist.github.com/AbhiAgarwal/8d2a817177c1197c3e28)

**Comment by ethanresnick** [comment]
@brentdur @ycp217 @AbhiAgarwal: I didn't read all of the discussion on slack (it was disappearing), but i just want to add a few things:
1. Having n-numbers is very important (as having those is linked, or soon will be, to getting $$$ from ASSBAC).
2. For swiping/rfid approaches, we discussed this last semester and @maxdumas looked into it, so please talk to him about what he discovered.
3. There are some interesting ideas [here](https://github.com/TechAtNYU/event-checkin/issues/8) and [here](https://github.com/TechAtNYU/intranet/issues/58) that really shouldn't get lost in this process!

**Comment by brentdur** [comment]
I think the first priority is making checkin easy, secure and familiar. The N #'s are important but there's also no way of getting them easily. In fact, I believe the only way for us is by manual entry, and that's not an option at the setup for an event. I'm much more leaning towards an idea abhi had, where we do a simple door checkin/signup and have them create an account later with the benefit of jobs (and ...) as a reward for doing it

**Comment by ethanresnick** [comment]
Agreed that n #s can be gotten later, and that fast experience at the event is probably the priority. there was hope at one point, though, that tapping an nyu id (fast) could get us an n-number somehow but, you'd have to talk to @maxdumas about that.

**Comment by maxdumas** [comment]
Yeah we determined that that would be largely impossible, because what is stored on the NYU IDs card, at least for RFID stuff, is a card-specific ID specifically for that. The only people who maintain the mappings of card-specific IDs to NNumbers is NYU Public Safety, and there is basically a 0% chance that they would let a club have their hands on that data.

That said, I believe what we discovered is that, when actually sliding the card, what is read from the magnetic strip contains the student's NNumber as well as that card-specific ID. That said I might be remembering incorrectly, the last time I looked at this was in May.

**Comment by brentdur** [comment]
My thought process was using the unique rfid to facilitate Checkin (the id is unique even if it's not the n number), but that logic can be changed for the n number method if you're sure that the magnetic strip gives both?

**Comment by brentdur** [comment]
@Abhi based off PR #24 would you call this closed. Or do you want to continue to iterate on the process?

**Comment by AbhiAgarwal** [comment]
@brentdur Let's close this. We'll re-open when we have new issues. I think @ycp217 made a couple more!

**Comment by juliepanda** [comment]
I opened a couple issues after yesterday's event, mainly improvement features.
