### ISSUE TITLE
Remove Express app?

### ISSUE THREAD

**Issue by AbhiAgarwal** [TechAtNYU/event-checkin#6]
Any chance we can remove the Express app off of this? Maybe switch it to an Angular app or something?

**Comment by ethanresnick** [comment]
That's probably doable, but we do need to think a bit first about what the permissions for the check in route should be, which will determine whether this service needs to have an API key, in which case we need to keep it with an express server. But if no key is needed, then we can certainly remove it!

**Comment by AbhiAgarwal** [comment]
@ethanresnick there isn't a key in the app right now!
